name: actions/create-release
on: [push]
jobs:
  retrieve-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: get repository changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -eo pipefail
        
        echo /repos/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY/pulls

        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY/pulls
