name: actions/create-release
on: [push]
jobs:
  retrieve-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Closed PRs
      id: closed-prs
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |

          git config --global user.name "ODM Team"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          last_release=$(gh release list --limit=1)
          last_release_date=$(echo $last_release | awk '{print $NF}')
          last_release_tag=$(echo $last_release | awk '{ print $2 }')
          
          closed_prs=$(gh pr list --base main --search "merged:>$last_release_date" --json "number,title,url")
          echo $closed_prs
          echo "--------"
          echo "release_version=v0.0.1" >> "$GITHUB_ENV"
          echo "${{ env.release_version }}"
          echo "--------"

          python ./bin/generate_release_note.py \
            --project "Data Order Management(ODM)" \
            --repo "data-order-management-api" \
            --current_tag "current_new_tag" \
            --previous_tag ${last_release_tag} \
            --previous_date ${last_release_date} \
            --changes "${closed_prs}" > ./docs/release_note/${last_release_tag}.md
          
          echo "::set-output name=TAG::${last_release_tag}"
          echo "TAG=${last_release_tag}" >> $GITHUB_OUTPUT

    - name: update file and push to remote
      environment:
        name: int
      run: |

        echo "${{ steps.closed-prs.outputs.TAG }}"

        git add -A
        git commit -m "Release ${{ steps.closed-prs.outputs.TAG}}"
        git push