name: actions/create-release
on: [push]
jobs:
  retrieve-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Closed PRs
      id: closed-prs
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          last_release=$(gh release list --limit=1)
          last_release_date=$(echo $last_release | awk '{print $NF}')
          last_release_tag=$(echo $last_release | awk '{ print $2 }')
          
          last_release=$(gh release list --limit=1 | awk '{print $NF}')
          closed_prs=$(gh pr list --base main --search "closed:>$last_release_date" --json "number,title,url")
          echo $closed_prs

          python ./bin/generate_release_note.py \
            --project "project_name" \
            --repo "repository_link" \
            --current_tag "current_new_tag" \
            --previous_tag "last_tag" \
            --previous_date "date" \
            --changes $closed_prs 