name: actions/create-release
on: [push]
jobs:
  retrieve-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List PRs
      id: pr-list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_list=$(gh pr list --state=merged)
        echo "::set-output name=pr_list::$pr_list"
        
    - name: Print PRs
      run: |
        echo ${{ steps.pr-list.outputs.pr_list }}
    
    - name: Get Last Tag
      id: last-tag
      run: |
        last_tag=$(git describe --tags --abbrev=0)
        last_commit=$(git rev-list -n 1 $last_tag)
        echo "::set-output name=last_tag::$last_tag"
        echo "::set-output name=last_commit::$last_commit"
        
    - name: Print Last Tag
      run: |
        echo "Last tag: ${{ steps.last-tag.outputs.last_tag }}"
        echo "Last commit: ${{ steps.last-tag.outputs.last_commit }}"
