name: actions/create-release
on: [push]
jobs:
  retrieve-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List PRs
      id: pr-list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_list=$(gh pr list --state=merged)
        echo "::set-output name=pr_list::$pr_list"
        
    - name: Print PRs
      run: |
        echo ${{ steps.pr-list.outputs.pr_list }}