name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  loadFeatures:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        name: set JSON
        run: echo "matrix={\"features\":[$(for i in $(find ./features -type f -name "*.feature");do echo -n " \"$i\","; done;)]}" >> "$GITHUB_OUTPUT"
      - name: Test
        run: echo ${{ steps.set-matrix.outputs.matrix }}
      
  execute-test-specification:
    needs: read-all-feature-files
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.loadFeatures.outputs.matrix) }}
    steps:
      - run: echo $${{ matrix.features }}