name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  read-all-feature-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-json
        name: set JSON
        run: echo "matrix={\"files\":{$(for i in $(find ./features -type f -name "*.feature");do echo -n " \"$i\","; done;)}}" >> "$GITHUB_OUTPUT"
      - name: Test
        run: echo ${{ steps.set-json.outputs.matrix }}
      
  execute-test-specification:
    needs: read-all-feature-files
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.read-all-feature-files.outputs.matrix) }}
    steps:
      - run: echo $${{ matrix.files }}