name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  read-all-feature-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set JSON
        run: echo "ABC={\"files\":{$(for i in $(find ./features -type f -name "*.feature");do echo " \"$i\","; done;)}};" >> $GITHUB_ENV
      - name: Test
        run: echo $ABC