name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env: 
  files: $${{ hashFiles(**/*.feature) }}
jobs:
  read-all-feature-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ env.files }}"